### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by Phill93** [trimstray/sandmap#54]
The installer is not macOS compatible.

**Comment by Go0s** [comment]
希望支持Mac，proxychains使用proxychains4替代，缺xterm

**Comment by trimstray** [comment]
Updated: [Requirements](https://github.com/trimstray/sandmap#requirements).

**Comment by rive-n** [comment]
> The installer is not macOS compatible.

I did not found info about current macos support state.
But i've forked and from now you can use it :)

https://github.com/rive-n/sandmap_MacOS
